import json,html
from pathlib import Path
def load(name): return json.loads(Path('results',name).read_text())
b=load('benchmark.json'); h=load('hard_scenarios.json'); a=load('ablations.json'); o=load('ood_robustness.json'); s=load('stress_test.json'); r=load('retrieval_eval.json'); c=load('calibration.json')
try:
    cov=load('coverage.json')['totals']['percent_covered']
except Exception:
    cov=None
rows=''.join(f"<tr><td>{html.escape(k.replace('_',' ').title())}</td><td>{v['accuracy']*100:.0f}%</td><td>{v['n']}</td></tr>" for k,v in h['by_category'].items())
ood_rows=''.join(f"<tr><td>{k.title()}</td><td>{v['accuracy']*100:.1f}%</td><td>{v['total']}</td></tr>" for k,v in o['ood_router']['by_label'].items())
page=f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BeliefWeave — Evaluation</title><style>
body{{font-family:Inter,system-ui,sans-serif;margin:0;background:#0a0c11;color:#f2f4f8}}main{{max-width:1120px;margin:auto;padding:45px 22px}}h1{{font-size:46px;margin:0}}.sub{{color:#9da5b3;font-size:19px;margin:6px 0 26px}}.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:14px;margin:22px 0}}.card{{background:#131720;border:1px solid #293141;border-radius:16px;padding:19px}}.big{{font-size:32px;font-weight:750}}.muted,.note{{color:#9da5b3}}table{{width:100%;border-collapse:collapse}}td,th{{padding:10px;border-bottom:1px solid #293141;text-align:left}}code{{background:#1c2330;padding:3px 7px;border-radius:7px}}.good{{color:#9be7b0}}.warn{{border-left:3px solid #d3a95b;padding-left:13px;color:#c9c0ad}}a{{color:#a8c7ff}}</style></head><body><main>
<a href="/">← Live demo</a><h1>BeliefWeave</h1><div class="sub">Evaluation dashboard · measured artifacts, with limitations shown alongside wins.</div>
<div class="grid"><div class="card"><div class="big">100,000</div><div class="muted">released synthetic longitudinal interactions</div></div><div class="card"><div class="big">{b['interactions']:,}</div><div class="muted">quick executable benchmark interactions</div></div><div class="card"><div class="big">{h['n_scenarios']}</div><div class="muted">deterministic hard scenarios</div></div><div class="card"><div class="big">{o['ood_router']['accuracy']*100:.1f}%</div><div class="muted">OOD router accuracy — open weakness</div></div></div>
<div class="grid"><div class="card"><h2>Temporal state</h2><div class="big good">{b['preference_reversal_old_belief_retirement_accuracy']['personal_world_model']*100:.0f}%</div><p class="muted">obsolete-belief retirement on controlled reversal probes; append-only = 0%.</p></div><div class="card"><h2>Retrieval Hit@1</h2><div class="big good">{r['semantic_local']['hit_at_1']*100:.1f}%</div><p class="muted">local hybrid vs {r['lexical']['hit_at_1']*100:.1f}% lexical on {r['n_cases']} controlled queries.</p></div><div class="card"><h2>Stress invariant</h2><div class="big good">{s['active_exact_contradictions']}</div><p class="muted">active exact likes/dislikes contradictions after {s['interactions']:,} stress interactions.</p></div></div>
<div class="card"><h2>Retrieval benchmark</h2><table><tr><th>Retriever</th><th>Hit@1</th><th>Hit@3</th><th>MRR</th><th>Stale leaks</th></tr><tr><td>Lexical baseline</td><td>{r['lexical']['hit_at_1']*100:.1f}%</td><td>{r['lexical']['hit_at_3']*100:.1f}%</td><td>{r['lexical']['mrr']:.3f}</td><td>{r['lexical']['stale_leaks']}</td></tr><tr><td>Local hybrid</td><td>{r['semantic_local']['hit_at_1']*100:.1f}%</td><td>{r['semantic_local']['hit_at_3']*100:.1f}%</td><td>{r['semantic_local']['mrr']:.3f}</td><td>{r['semantic_local']['stale_leaks']}</td></tr></table><p class="note">Controlled relevance benchmark with shuffled insertion order, context-specific cases, distractors and superseded-memory probes.</p></div>
<div class="grid"><div class="card"><h2>Reversal ablation</h2><p>Append-only: <b>{a['reversal_retirement_accuracy']['append_only']*100:.0f}%</b></p><p>Latest-predicate: <b>{a['reversal_retirement_accuracy']['latest_predicate']*100:.0f}%</b></p><p>Full PWM: <b>{a['reversal_retirement_accuracy']['full_pwm']*100:.0f}%</b></p></div><div class="card"><h2>Temporary expiry</h2><p>Append-only: <b>{a['temporary_expiry_accuracy']['append_only']*100:.0f}%</b></p><p>Latest-predicate: <b>{a['temporary_expiry_accuracy']['latest_predicate']*100:.0f}%</b></p><p>Full PWM: <b>{a['temporary_expiry_accuracy']['full_pwm']*100:.0f}%</b></p></div></div>
<div class="card"><h2>Regression suite</h2><table><tr><th>Category</th><th>Accuracy</th><th>N</th></tr>{rows}</table><p class="note">These scenarios are generated from controlled templates and should be read as regression coverage, not broad generalization.</p></div>
<div class="card"><h2>Linguistic distribution shift</h2><table><tr><th>Router class</th><th>Accuracy</th><th>N</th></tr>{ood_rows}</table><p class="warn">The lightweight local TF–IDF router reaches only {o['ood_router']['accuracy']*100:.1f}% on held-out paraphrase families. This is intentionally exposed: replacing it with a stronger semantic encoder or trained LLM extractor is the clearest next model-quality milestone.</p></div>
<div class="grid"><div class="card"><h2>Selective memory writing</h2><div class="big good">{next(x for x in c['selective_prediction'] if x['threshold']==0.7)['accuracy']*100:.1f}%</div><p class="muted">OOD accuracy when the router only accepts candidates at confidence ≥ 0.70; coverage {next(x for x in c['selective_prediction'] if x['threshold']==0.7)['coverage']*100:.1f}%.</p></div><div class="card"><h2>Calibration</h2><div class="big">{c['ece']:.3f}</div><p class="muted">Expected calibration error on the held-out paraphrase set. Low-confidence candidates are intentionally dropped instead of persisted.</p></div><div class="card"><h2>Test coverage</h2><div class="big good">{(cov if cov is not None else 0):.1f}%</div><p class="muted">Line coverage from the current regression suite; CI enforces ≥90%.</p></div></div>
<div class="card"><h2>Safety findings that changed the architecture</h2><p><code>My friend says I love sushi.</code> initially risked attribution poisoning → third-party guard.</p><p>Learned conflict classification once tried to supersede an unrelated preference with a goal → structural safety gates.</p><p>Same-predicate values such as <code>I love sushi</code> + <code>I love jazz</code> are now additive by default rather than incorrectly treated as drift.</p></div>
<p class="note">All numeric results here are from synthetic, deterministic, or local stress evaluations included in this repository. No human-user performance claim is made.</p></main></body></html>'''
Path('dashboard/index.html').write_text(page); print('wrote dashboard/index.html')
